import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import vikeReact from 'vike-react/config';
import vikeTypedoc from 'vike-plugin-typedoc/config';
import type { Config } from 'vike/types';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

// Default config (can be overridden by pages)
// https://vike.dev/config

export default {
  // https://vike.dev/head-tags
  title: 'isolated-workers',
  description: 'Type-safe worker processes with end-to-end message contracts',

  // Enable static site generation
  prerender: true,
  passToClient: ['navigation'],

  extends: [vikeReact, vikeTypedoc],

  typedoc: {
    // .typedoc/ at the repo root contains api.json (generated by packages/isolated-workers typedoc)
    typedocDir: join(__dirname, '../../.typedoc'),
    // api.json → slug "api" → map to the npm package name
    packageNames: { api: 'isolated-workers' },
  },
} satisfies Config;
