import path from 'node:path'
import rehypeShiki from '@shikijs/rehype'
import { parseCodeBlockMeta, rehypeCodeBlockChrome, titleTransformer } from '../server/utils/rehype-code-block-chrome.js'

// process.cwd() during build = docs-site/, so ../  = repo root
const repoRoot = path.resolve(process.cwd(), '..')

export default {
  // .typedoc/ at the repo root contains api.json (generated by packages/isolated-workers typedoc)
  typedocDir: path.join(repoRoot, '.typedoc'),
  // api.json → slug "api" → map to the npm package name
  packageNames: { api: 'isolated-workers' },
  // Syntax highlighting + terminal chrome for API page code blocks
  rehypePlugins: [
    [rehypeShiki, { theme: 'github-dark', addLanguageClass: true, parseMetaString: parseCodeBlockMeta, transformers: [titleTransformer] }],
    rehypeCodeBlockChrome,
  ],
}
