packages:
  - 'packages/*'
  - 'docs'
  - 'examples'
  - 'e2e'
  - 'tools/scripts'
  - 'type-tests'

catalog:
  '@nx/devkit': 22.4.3
  '@nx/js': 22.4.3
  '@nx/workspace': 22.4.3
  '@nx/eslint': 22.4.3
  '@nx/eslint-plugin': 22.4.3
  '@nx/vite': 22.4.3
  '@nx/vitest': 22.4.3
  '@nx/web': 22.4.3
  '@swc-node/register': ~1.11.1
  '@swc/core': ~1.15.3
  '@swc/helpers': ~0.5.17
  '@types/node': 20.11.30
  '@typescript-eslint/eslint-plugin': ^8.24.0
  '@typescript-eslint/parser': ^8.24.0
  '@vitest/coverage-v8': ^1.0.4
  eslint: ^9.15.0
  eslint-config-prettier: 10.1.8
  nx: 22.4.3
  prettier: ^2.6.2
  tslib: ^2.3.0
  typescript: ^5.7.2
  vite: ^5.4.0
  vitest: ^1.3.1

