id: error-handling
title: Error Handling
description: |
  Demonstrates how errors thrown in worker handlers propagate back to the host,
  including error messages and proper cleanup.
entryPoint: host.ts
fileMap:
  './messages.ts': 'messages.ts'
  './host.ts': 'host.ts'
  './worker.ts': 'worker.ts'
commands:
  - command: 'pnpm run:error-handling'
    title: 'Run the example'
    assertions:
      - contains: 'Test 1: 10 / 2'
      - contains: 'Result: 5'
      - contains: 'Test 2: 10 / 0 (should error)'
      - contains: 'Division by zero'
      - contains: 'All tests passed'
